version: "3.4"

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  backend:
    container_name: ${BE_CONTAINER_NAME}
    environment:
      - ConnectionStrings__ShoppingListContext=Host=${DB_CONTAINER_NAME};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS}
    image: shopping-list-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    # TODO: only for debug - make separate compose file
    ports:
      - 5000:3000
    depends_on:
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  frontend:
    container_name: ${FE_CONTAINER_NAME}
    environment:
      - backend_host=${BE_CONTAINER_NAME}
    image: shopping-list-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 666:3000
    depends_on:
      - backend
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
